export const invitados = [
  { id: "A7K2Q", invitado: "FAMILIA MATA RUIZ", pases: 3 },
  { id: "P9X4M", invitado: "FAMILIA LOZANO MATA", pases: 2 },
  { id: "R2J8T", invitado: "DELIA RUIZ", pases: 2 },
  { id: "N5W1C", invitado: "FAMILIA MATA MARMOLEJO", pases: 5 },
  { id: "H8F6L", invitado: "FAMILIA DZUL HUICAB", pases: 4 },
  { id: "Q3B9Y", invitado: "FAMILIA PEREZ DZUL", pases: 2 },
  { id: "T7D4K", invitado: "ROSA HUICAN", pases: 1 },
  { id: "M1Z8P", invitado: "ANTONIO HUICAB", pases: 1 },
  { id: "V6R2N", invitado: "MAURO", pases: 1 },
  { id: "C9L5X", invitado: "CARLOS", pases: 1 },
  { id: "J4Q7A", invitado: "MIRNA", pases: 4 },
  { id: "E8H3W", invitado: "PABLO", pases: 4 },
  { id: "Y2M6F", invitado: "MELANNI", pases: 1 },
  { id: "L5T9R", invitado: "FAMILIA FLORES PLASENCIA", pases: 2 },
  { id: "B1N4V", invitado: "FAMILIA BARCENAS GONZALEZ", pases: 3 },
  { id: "X7C2J", invitado: "FAMILIA RUIZ BONILLA", pases: 3 },
  { id: "K9P5D", invitado: "FAMILIA PEDROZA DELGADO", pases: 3 },
  { id: "F3W8Q", invitado: "FAMILIA BARBA VARELA", pases: 2 },
  { id: "U6A1L", invitado: "FAMILIA PEREZ LLAMAS", pases: 2 },
  { id: "G2R9M", invitado: "CARMEN VAZQUEZ", pases: 1 },
  { id: "D8Y4H", invitado: "BRENDA CARMONA", pases: 1 },
  { id: "S5K1T", invitado: "MARTIN VILLANUEVA", pases: 1 },
  { id: "W9J6B", invitado: "OSCAR RUIZ", pases: 1 },
  { id: "Z4P7E", invitado: "JORGE LUIS CANO", pases: 1 },
  { id: "I3X8N", invitado: "ANGEL PEDROZA", pases: 1 },
  { id: "O1F5C", invitado: "EDUARDO", pases: 1 },
  { id: "R8L2V", invitado: "ANGELICA", pases: 1 },
  { id: "Q6T9G", invitado: "SONIA OROPEZA", pases: 1 },
  { id: "M4B7K", invitado: "DENISSE", pases: 1 }
];
